# Basic commands for Docker
alias dkr='docker'                          # Docker <params>        
alias dkrc='docker-compose'                 # Docker Compose <params>
alias dkrbuild='docker build . -t'          # Build image <params>
alias dkrup='docker-compose up -d'          # Start containers
alias dkrdown='docker-compose down'         # Stop containers
alias dkrexec='docker exec -it'             # Execute command in container <params>
alias dkrlogs='docker logs -f'              # Show logs <params>
alias dkrps='docker ps'                     # Show running containers
alias dkrpsa='docker ps -a'                 # Show all containers
alias dkrrm='docker rm'                     # Remove container <params>
alias dkrrmi='docker rmi'                   # Remove image <params>
alias dkrstop='docker stop'                 # Stop container <params>
alias dkrstart='docker start'               # Start container <params>
alias dkrrestart='docker restart'           # Restart container <params>
alias dkrprune='docker system prune -af'    # Prune all containers, images, and volumes
alias dkrimages='docker images'             # Show images
alias dkrvolumes='docker volume ls'         # Show volumes
alias dkrclean='docker rm $(docker ps -a -q) && docker rmi $(docker images -q) && docker volume rm $(docker volume ls -q)' # Clean all containers, images, and volumes
